name: fish_classification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - opencv
  - numpy
  - tqdm
  - scikit-learn
  - matplotlib
  - pillow
  - pip
  - pip:
      - kagglehub